[package]
name = "qiskit"
version = "0.1.0"
authors = ["zaba505 <cakub6@gmx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
